reference_genomes:
    - name: hg38
      species: homo sapiens
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/hg38/hg38.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/hg38/hg38.fa.fai
      bowtie: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/hg38/hg38_bowtie/hg38
      bowtie2: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/hg38/hg38_bowtie2/hg38
      split: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/hg38/hg38_split/
      link: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
      source: UCSC Genome Browser
      scrubString: random\|alt\|Un
    - name: humanRibo
      species: homo sapiens
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/ensembleBiomartRibosomalSequence.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/ensembleBiomartRibosomalSequence.fa.fai
      link: https://useast.ensembl.org/
      source: Enesemble BioMart
    - name: humanTrna
      species: homo sapiens
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/rnaCentral_tRNA.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/homo_sapiens/rnaCentral_tRNA.fa.fai
      link: rnacentral.org/
      source: RNA Central
    - name: mycoG37
      species: mycoplasma
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/Mycoplasma/genitalium_G37/GCF_000027325.1_ASM2732v1_genomic.fna
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/Mycoplasma/genitalium_G37/GCF_000027325.1_ASM2732v1_genomic.fna.fai
      link: https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000027325.1/
      source: NCBI

annotations:
    - name: NCBIrefSeq
      genome: hg38
      bed_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/homo_sapiens/ncbiRefSeqCurated.hg38.bed
      gtf_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/homo_sapiens/ncbiRefSeqCurated.hg38.gtf
      link: https://genome.ucsc.edu/cgi-bin/hgTables
      instructions: group:genes;track:NCBI RefSeq;table:ncbiRefSeqCurated
      source: UCSC Genome Browser

data_sets:
    - name: D2R2_17_Yes
      paired: True
      depleted: Yes
      class: Free_RNA
      path: data/raw/sequence/D2R2_17/
      readsfile1: D2R2_17-Free_RNA_TAATACAG-ATATTCAC_R1.fastq
      readsfile2: D2R2_17-Free_RNA_TAATACAG-ATATTCAC_R2.fastq
      subgroups: [all,depleted,Free_RNA]
    - name: D2R2_17_No
      paired: True
      depleted: No
      class: Free_RNA
      path: data/raw/sequence/D2R2_17/
      readsfile1: D2R2_17-Free_RNA_TATCGCAC-CTTAGTGT_R1.fastq
      readsfile2: D2R2_17-Free_RNA_TATCGCAC-CTTAGTGT_R2.fastq
      subgroups: [all,undepleted,Free_RNA]
    - name: D2R2_18_Yes
      paired: True
      depleted: Yes
      class: Free_RNA
      path: data/raw/sequence/D2R2_18/
      readsfile1: D2R2_18-Free_RNA_CGGCGTGA-GCGCCTGT_R1.fastq
      readsfile2: D2R2_18-Free_RNA_CGGCGTGA-GCGCCTGT_R2.fastq
      subgroups: [all,depleted,Free_RNA]
    - name: D2R2_18_No
      paired: True
      depleted: No
      class: Free_RNA
      path: data/raw/sequence/D2R2_18/
      readsfile1: D2R2_18-Free_RNA_CGCTATGT-TCCGACAC_R1.fastq
      readsfile2: D2R2_18-Free_RNA_CGCTATGT-TCCGACAC_R2.fastq
      subgroups: [all,undepleted,Free_RNA]
    - name: D2R2_19_Yes
      paired: True
      depleted: Yes
      class: Free_RNA
      path: data/raw/sequence/D2R2_19/
      readsfile1: D2R2_19-Free_RNA_ATGTAAGT-ACTCTATG_R1.fastq
      readsfile2: D2R2_19-Free_RNA_ATGTAAGT-ACTCTATG_R2.fastq
      subgroups: [all,depleted,Free_RNA]
    - name: D2R2_19_No
      paired: True
      depleted: No
      class: Free_RNA
      path: data/raw/sequence/D2R2_19/
      readsfile1: D2R2_19-Free_RNA_GTATGTTC-AACAGGAA_R1.fastq
      readsfile2: D2R2_19-Free_RNA_GTATGTTC-AACAGGAA_R2.fastq
      subgroups: [all,undepleted,Free_RNA]
    - name: D2R2_20_Yes
      paired: True
      depleted: Yes
      class: Free_RNA
      path: data/raw/sequence/D2R2_20/
      readsfile1: D2R2_20-Free_RNA_GCACGGAC-GTCTCGCA_R1.fastq
      readsfile2: D2R2_20-Free_RNA_GCACGGAC-GTCTCGCA_R2.fastq
      subgroups: [all,depleted,Free_RNA]
    - name: D2R2_20_No
      paired: True
      depleted: No
      class: Free_RNA
      path: data/raw/sequence/D2R2_20/
      readsfile1: D2R2_20-Free_RNA_ACGCACCT-GGTGAAGG_R1.fastq
      readsfile2: D2R2_20-Free_RNA_ACGCACCT-GGTGAAGG_R2.fastq
      subgroups: [all,undepleted,Free_RNA]
    - name: D2R2_13_Yes
      paired: True
      depleted: Yes
      class: P100_pellet
      path: data/raw/sequence/D2R2_13/
      readsfile1: D2R2_13-P100_pellet_CCAAGTCT-AAGGATGA_R1.fastq
      readsfile2: D2R2_13-P100_pellet_CCAAGTCT-AAGGATGA_R2.fastq
      subgroups: [all,depleted,P100_pellet]
    - name: D2R2_13_No
      paired: True
      depleted: No
      class: P100_pellet
      path: data/raw/sequence/D2R2_13/
      readsfile1: D2R2_13-P100_pellet_AGGTTATA-CAGTTCCG_R1.fastq
      readsfile2: D2R2_13-P100_pellet_AGGTTATA-CAGTTCCG_R2.fastq
      subgroups: [all,undepleted,P100_pellet]
    - name: D2R2_14_Yes
      paired: True
      depleted: Yes
      class: P100_pellet
      path: data/raw/sequence/D2R2_14/
      readsfile1: D2R2_14-P100_pellet_TTGGACTC-GGAAGCAG_R1.fastq
      readsfile2: D2R2_14-P100_pellet_TTGGACTC-GGAAGCAG_R2.fastq
      subgroups: [all,depleted,P100_pellet]
    - name: D2R2_14_No
      paired: True
      depleted: No
      class: P100_pellet
      path: data/raw/sequence/D2R2_14/
      readsfile1: D2R2_14-P100_pellet_GAACCGCG-TGACCTTA_R1.fastq
      readsfile2: D2R2_14-P100_pellet_GAACCGCG-TGACCTTA_R2.fastq
      subgroups: [all,undepleted,P100_pellet]
    - name: D2R2_15_Yes
      paired: True
      depleted: Yes
      class: P100_pellet
      path: data/raw/sequence/D2R2_15/
      readsfile1: D2R2_15-P100_pellet_GGCTTAAG-TCGTGACC_R1.fastq
      readsfile2: D2R2_15-P100_pellet_GGCTTAAG-TCGTGACC_R2.fastq
      subgroups: [all,depleted,P100_pellet]
    - name: D2R2_15_No
      paired: True
      depleted: No
      class: P100_pellet
      path: data/raw/sequence/D2R2_15/
      readsfile1: D2R2_15-P100_pellet_CTCACCAA-CTAGGCAA_R1.fastq
      readsfile2: D2R2_15-P100_pellet_CTCACCAA-CTAGGCAA_R2.fastq
      subgroups: [all,undepleted,P100_pellet]
    - name: D2R2_16_Yes
      paired: True
      depleted: Yes
      class: P100_pellet
      path: data/raw/sequence/D2R2_16/
      readsfile1: D2R2_16-P100_pellet_AATCCGGA-CTACAGTT_R1.fastq
      readsfile2: D2R2_16-P100_pellet_AATCCGGA-CTACAGTT_R2.fastq
      subgroups: [all,depleted,P100_pellet]
    - name: D2R2_16_No
      paired: True
      depleted: No
      class: P100_pellet
      path: data/raw/sequence/D2R2_16/
      readsfile1: D2R2_16-P100_pellet_TCTGTTGG-TCGAATGG_R1.fastq
      readsfile2: D2R2_16-P100_pellet_TCTGTTGG-TCGAATGG_R2.fastq
      subgroups: [all,undepleted,P100_pellet]
    - name: D2R2_09_Yes
      paired: True
      depleted: Yes
      class: P40_pellet
      path: data/raw/sequence/D2R2_09/
      readsfile1: D2R2_09-P40_pellet_AGTTCAGG-CCAACAGA_R1.fastq
      readsfile2: D2R2_09-P40_pellet_AGTTCAGG-CCAACAGA_R2.fastq
      subgroups: [all,depleted,P40_pellet]
    - name: D2R2_09_No
      paired: True
      depleted: No
      class: P40_pellet
      path: data/raw/sequence/D2R2_09/
      readsfile1: D2R2_09-P40_pellet_AACTGTAG-ACGCCGCA_R1.fastq
      readsfile2: D2R2_09-P40_pellet_AACTGTAG-ACGCCGCA_R2.fastq
      subgroups: [all,undepleted,P40_pellet]
    - name: D2R2_10_Yes
      paired: True
      depleted: Yes
      class: P40_pellet
      path: data/raw/sequence/D2R2_10/
      readsfile1: D2R2_10-P40_pellet_GACCTGAA-TTGGTGAG_R1.fastq
      readsfile2: D2R2_10-P40_pellet_GACCTGAA-TTGGTGAG_R2.fastq
      subgroups: [all,depleted,P40_pellet]
    - name: D2R2_10_No
      paired: True
      depleted: No
      class: P40_pellet
      path: data/raw/sequence/D2R2_10/
      readsfile1: D2R2_10-P40_pellet_GGTCACGA-GTATTATG_R1.fastq
      readsfile2: D2R2_10-P40_pellet_GGTCACGA-GTATTATG_R2.fastq
      subgroups: [all,undepleted,P40_pellet]
    - name: D2R2_11_Yes
      paired: True
      depleted: Yes
      class: P40_pellet
      path: data/raw/sequence/D2R2_11/
      readsfile1: D2R2_11-P40_pellet_TCTCTACT-CGCGGTTC_R1.fastq
      readsfile2: D2R2_11-P40_pellet_TCTCTACT-CGCGGTTC_R2.fastq
      subgroups: [all,depleted,P40_pellet]
    - name: D2R2_11_No
      paired: True
      depleted: No
      class: P40_pellet
      path: data/raw/sequence/D2R2_11/
      readsfile1: D2R2_11-P40_pellet_CTGCTTCC-GATAGATC_R1.fastq
      readsfile2: D2R2_11-P40_pellet_CTGCTTCC-GATAGATC_R2.fastq
      subgroups: [all,undepleted,P40_pellet]
    - name: D2R2_12_Yes
      paired: True
      depleted: Yes
      class: P40_pellet
      path: data/raw/sequence/D2R2_12/
      readsfile1: D2R2_12-P40_pellet_CTCTCGTC-TATAACCT_R1.fastq
      readsfile2: D2R2_12-P40_pellet_CTCTCGTC-TATAACCT_R2.fastq
      subgroups: [all,depleted,P40_pellet]
    - name: D2R2_12_No
      paired: True
      depleted: No
      class: P40_pellet
      path: data/raw/sequence/D2R2_12/
      readsfile1: D2R2_12-P40_pellet_TCATCCTT-AGCGAGCT_R1.fastq
      readsfile2: D2R2_12-P40_pellet_TCATCCTT-AGCGAGCT_R2.fastq
      subgroups: [all,undepleted,P40_pellet]
    - name: D2R2_01_Yes
      paired: True
      depleted: Yes
      class: RNA_Control
      path: data/raw/sequence/D2R2_01/
      readsfile1: D2R2_01-RNA_Control_CCGCGGTT-AGCGCTAG_R1.fastq
      readsfile2: D2R2_01-RNA_Control_CCGCGGTT-AGCGCTAG_R2.fastq
      subgroups: [all,depleted,RNA_Control]
    - name: D2R2_01_No
      paired: True
      depleted: No
      class: RNA_Control
      path: data/raw/sequence/D2R2_01/
      readsfile1: D2R2_01-RNA_Control_CAATTAAC-CGAGATAT_R1.fastq
      readsfile2: D2R2_01-RNA_Control_CAATTAAC-CGAGATAT_R2.fastq
      subgroups: [all,undepleted,RNA_Control]
    - name: D2R2_02_Yes
      paired: True
      depleted: Yes
      class: RNA_Control
      path: data/raw/sequence/D2R2_02/
      readsfile1: D2R2_02-RNA_Control_TTATAACC-GATATCGA_R1.fastq
      readsfile2: D2R2_02-RNA_Control_TTATAACC-GATATCGA_R2.fastq
      subgroups: [all,depleted,RNA_Control]
    - name: D2R2_02_No
      paired: True
      depleted: No
      class: RNA_Control
      path: data/raw/sequence/D2R2_02/
      readsfile1: D2R2_02-RNA_Control_TGGCCGGT-TAGAGCGC_R1.fastq
      readsfile2: D2R2_02-RNA_Control_TGGCCGGT-TAGAGCGC_R2.fastq
      subgroups: [all,undepleted,RNA_Control]
    - name: D2R2_03_Yes
      paired: True
      depleted: Yes
      class: RNA_Control
      path: data/raw/sequence/D2R2_03/
      readsfile1: D2R2_03-RNA_Control_GGACTTGG-CGCAGACG_R1.fastq
      readsfile2: D2R2_03-RNA_Control_GGACTTGG-CGCAGACG_R2.fastq
      subgroups: [all,depleted,RNA_Control]
    - name: D2R2_03_No
      paired: True
      depleted: No
      class: RNA_Control
      path: data/raw/sequence/D2R2_03/
      readsfile1: D2R2_03-RNA_Control_AGTACTCC-AACCTGTT_R1.fastq
      readsfile2: D2R2_03-RNA_Control_AGTACTCC-AACCTGTT_R2.fastq
      subgroups: [all,undepleted,RNA_Control]
    - name: D2R2_04_Yes
      paired: True
      depleted: Yes
      class: RNA_Control
      path: data/raw/sequence/D2R2_04/
      readsfile1: D2R2_04-RNA_Control_AAGTCCAA-TATGAGTA_R1.fastq
      readsfile2: D2R2_04-RNA_Control_AAGTCCAA-TATGAGTA_R2.fastq
      subgroups: [all,depleted,RNA_Control]
    - name: D2R2_04_No
      paired: True
      depleted: No
      class: RNA_Control
      path: data/raw/sequence/D2R2_04/
      readsfile1: D2R2_04-RNA_Control_GACGTCTT-GGTTCACC_R1.fastq
      readsfile2: D2R2_04-RNA_Control_GACGTCTT-GGTTCACC_R2.fastq
      subgroups: [all,undepleted,RNA_Control]
    - name: D2R2_05_Yes
      paired: True
      depleted: Yes
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_05/
      readsfile1: D2R2_05-Total_ExRNA_ATCCACTG-AGGTGCGT_R1.fastq
      readsfile2: D2R2_05-Total_ExRNA_ATCCACTG-AGGTGCGT_R2.fastq
      subgroups: [all,depleted,Total_ExRNA]
    - name: D2R2_05_No
      paired: True
      depleted: No
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_05/
      readsfile1: D2R2_05-Total_ExRNA_TGCGAGAC-CATTGTTG_R1.fastq
      readsfile2: D2R2_05-Total_ExRNA_TGCGAGAC-CATTGTTG_R2.fastq
      subgroups: [all,undepleted,Total_ExRNA]
    - name: D2R2_06_Yes
      paired: True
      depleted: Yes
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_06/
      readsfile1: D2R2_06-Total_ExRNA_GCTTGTCA-GAACATAC_R1.fastq
      readsfile2: D2R2_06-Total_ExRNA_GCTTGTCA-GAACATAC_R2.fastq
      subgroups: [all,depleted,Total_ExRNA]
    - name: D2R2_06_No
      paired: True
      depleted: No
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_06/
      readsfile1: D2R2_06-Total_ExRNA_CATAGAGT-TGCCACCA_R1.fastq
      readsfile2: D2R2_06-Total_ExRNA_CATAGAGT-TGCCACCA_R2.fastq
      subgroups: [all,undepleted,Total_ExRNA]
    - name: D2R2_07_Yes
      paired: True
      depleted: Yes
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_07/
      readsfile1: D2R2_07-Total_ExRNA_CAAGCTAG-ACATAGCG_R1.fastq
      readsfile2: D2R2_07-Total_ExRNA_CAAGCTAG-ACATAGCG_R2.fastq
      subgroups: [all,depleted,Total_ExRNA]
    - name: D2R2_07_No
      paired: True
      depleted: No
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_07/
      readsfile1: D2R2_07-Total_ExRNA_ACAGGCGC-CTCTGCCT_R1.fastq
      readsfile2: D2R2_07-Total_ExRNA_ACAGGCGC-CTCTGCCT_R2.fastq
      subgroups: [all,undepleted,Total_ExRNA]
    - name: D2R2_08_Yes
      paired: True
      depleted: Yes
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_08/
      readsfile1: D2R2_08-Total_ExRNA_TGGATCGA-GTGCGATA_R1.fastq
      readsfile2: D2R2_08-Total_ExRNA_TGGATCGA-GTGCGATA_R2.fastq
      subgroups: [all,depleted,Total_ExRNA]
    - name: D2R2_08_No
      paired: True
      depleted: No
      class: Total_ExRNA
      path: data/raw/sequence/D2R2_08/
      readsfile1: D2R2_08-Total_ExRNA_GTGAATAT-TCTCATTC_R1.fastq
      readsfile2: D2R2_08-Total_ExRNA_GTGAATAT-TCTCATTC_R2.fastq
      subgroups: [all,undepleted,Total_ExRNA]
